version: "3"
services:
  db_image:
    build: db/
    ports:
      - 5433:5433
    networks:
      custom_net:
        ipv4_address: 10.5.0.5
  bot:
    build: bot/
    ports:
      - 5001:5001
    networks:
      custom_net:
        ipv4_address: 10.5.0.6
    restart: always
    depends_on:
      - db_image
  db_repl_image:
    build: db_repl/
    depends_on:
      - bot
    restart: always
    networks:
      custom_net:
        ipv4_address: 10.5.0.7

volumes:
  db:
    driver: local

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
