 - name: Deployment
   hosts: all
   become: yes

   tasks:

   - name: Install Git
     apt:
       name:
         - git
       state: latest

   - name: Install docker and docker-compose
     ansible.builtin.shell: |
      apt update &&
      apt install -y ca-certificates curl
     ansible.builtin.shell: |
      install -m 0755 -d /etc/apt/keyrings &&
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc &&
      chmod a+r /etc/apt/keyrings/docker.asc
     ansible.builtin.shell: |
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null &&
      apt update &&
      apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

   - name: Create a directory
     ansible.builtin.file:
      path: /home/ubuntu/deployment
      state: directory

   - name: Clone a github repository
     ansible.builtin.shell: |
      cd /home/ubuntu/deployment &&
      git clone -b docker https://github.com/H0ho1/DevOps_PT-Start.git
#     git:
#       repo: https://github.com/H0ho1/DevOps_PT-Start.git
#       dest: /home/ubuntu/deployment
#       clone: yes
#       update: yes

   - name: Launch infracstucture
     ansible.builtin.shell: |
      cd /home/ubuntu/deployment/DevOps_PT-Start &&
      docker compose up
